---
apiVersion: v2
name: snapserver
description: Deploy Snapcast server

type: application
version: 0.1.1
appVersion: "v0.26.0"

dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
