---
apiVersion: v2
name: mopidy
description: Deploy Mopidy music server.

type: application
version: 0.5.6
appVersion: "v3.69.3"

dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
